In [11]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0, 0, 0],  # Sample 1: Class 1
    [0, 1, 0, 0, 0],  # Sample 2: Class 2
    [0, 0, 1, 0, 0],# Sample 3: Class 3
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]
])

# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1, 2.0, 2.5],  # Sample 1
    [0.5, 2.5, 0.2, 2.5, 0.5],  # Sample 2
    [0.1, 0.2, 3.0, 1.0, 2.0],# Sample 3
    [0.5, 2.0, 0.2, 2.0, 1.0],  # Sample 2
    [2.0, 0.2, 3.0, 1.0, 2.0],

])

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)

Softmax Probabilities:
 [[0.24002865 0.08830161 0.03590075 0.24002865 0.39574034]
 [0.05708111 0.42177553 0.04228673 0.42177553 0.05708111]
 [0.03398492 0.03755915 0.61764691 0.08358942 0.2272196 ]
 [0.08095254 0.36280409 0.05997111 0.36280409 0.13346817]
 [0.19042323 0.03147675 0.517624   0.07005279 0.19042323]]

Log of Softmax Probabilities:
 [[-1.42699699 -2.42699699 -3.32699699 -1.42699699 -0.92699699]
 [-2.86328203 -0.86328203 -3.16328203 -0.86328203 -2.86328203]
 [-3.38183833 -3.28183833 -0.48183833 -2.48183833 -1.48183833]
 [-2.51389228 -1.01389228 -2.81389228 -1.01389228 -2.01389228]
 [-1.65850616 -3.45850616 -0.65850616 -2.65850616 -1.65850616]]

y_true * log(probs):
 [[-1.42699699 -0.         -0.         -0.         -0.        ]
 [-0.         -0.86328203 -0.         -0.         -0.        ]
 [-0.         -0.         -0.48183833 -0.         -0.        ]
 [-0.         -0.         -0.         -1.01389228 -0.        ]
 [-0.         -0.         -0.         -0.         -1.65850616]

In [10]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0],  # Sample 1: Class 1
    [0, 1, 0],  # Sample 2: Class 2
    [0, 0, 1],# Sample 3: Class 3
    [1, 0, 0],
    [0, 1, 0]
])

# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1],  # Sample 1
    [0.5, 2.5, 0.2],  # Sample 2
    [0.1, 0.2, 3.0],# Sample 3
    [0.2, 0.1, 2.0],
    [2.0, 0.1, 0.2],
])

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)

Softmax Probabilities:
 [[0.65900114 0.24243297 0.09856589]
 [0.10953053 0.80932725 0.08114221]
 [0.04931133 0.05449744 0.89619123]
 [0.12571524 0.11375186 0.7605329 ]
 [0.7605329  0.11375186 0.12571524]]

Log of Softmax Probabilities:
 [[-0.41703002 -1.41703002 -2.31703002]
 [-2.21155193 -0.21155193 -2.51155193]
 [-3.00960146 -2.90960146 -0.10960146]
 [-2.07373591 -2.17373591 -0.27373591]
 [-0.27373591 -2.17373591 -2.07373591]]

y_true * log(probs):
 [[-0.41703002 -0.         -0.        ]
 [-0.         -0.21155193 -0.        ]
 [-0.         -0.         -0.10960146]
 [-2.07373591 -0.         -0.        ]
 [-0.         -2.17373591 -0.        ]]

CE Loss per Sample: [0.41703002 0.21155193 0.10960146 2.07373591 2.17373591]

Average CE Loss for the Dataset: 0.9971310442355588
